### ISSUE TITLE
Usage of files within .cache in bazel-build tensorflow leads to errors when package is compiled

### ISSUE THREAD

**Issue by deeptf** [tradr-project/tensorflow_ros_cpp#2]
Here are some files with in tensorflow-include-base which has files linked to .cache in /home/user directory. During a clean installation, it is followed to delete this cache files. If these cache files are deleted there is catkin_make error for this package. 

bazel-bin -> /home/user/.cache/bazel/_bazel_user/6f91ff23d6c28d093ed7767464121bf4/execroot/org_tensorflow/bazel-out/k8-opt/bin/
bazel-genfiles -> /home/user/.cache/bazel/_bazel_user/6f91ff23d6c28d093ed7767464121bf4/execroot/org_tensorflow/bazel-out/k8-opt/genfiles/
bazel-out -> /home/user/.cache/bazel/_bazel_user/6f91ff23d6c28d093ed7767464121bf4/execroot/org_tensorflow/bazel-out/
bazel-tensorflow -> /home/user/.cache/bazel/_bazel_user/6f91ff23d6c28d093ed7767464121bf4/execroot/org_tensorflow/
bazel-testlogs -> /home/user/.cache/bazel/_bazel_user/6f91ff23d6c28d093ed7767464121bf4/execroot/org_tensorflow/bazel-out/k8-opt/testlogs/

Can you help provide more insight on what exactly is needed from these cache files or provide if there is a cleaner way to handle this part? Thanks!

**Comment by peci1** [comment]
I haven't found a cleaner way with bazel. You basically need the library files (`libtensorflow.so` and `libtensorfow_framework.so`, maybe some more). If you find a folder with predictable path where you can find these build artifacts, please let me know. So far, the bazel build option depends on the .cache folder not being deleted.

**Comment by peci1** [comment]
And also some generated include files are needed...

**Comment by deeptf** [comment]
I find the libtensorflow.so but I am not exactly sure about what other files are required from .cache. I can investigate more when I find time and re-open the issue and post any solution I find. Thanks!

**Comment by peci1** [comment]
Ok, I'm just curious why don't you build TF via bazel again to regenerate the .cache directory contents...

**Comment by deeptf** [comment]
I can as a quick solution. But I just prefer not to have packages depending on .cache folder and was wondering if there is a different way to use. Thanks again for the great work and your answers.

**Comment by peci1** [comment]
Great, I understand you now :) What you could actually do is (manually) copy the used files from .cache to a different directory and point CMake to that one instead.
