### ISSUE TITLE
fatal error: absl/strings/str_join.h: No such file or directory

### ISSUE THREAD

**Issue by eraserpencil** [tradr-project/tensorflow_ros_cpp#6]
**Tensorflow (please complete the following information):**
 - Version: 1.8.0 and 1.140 has the issue
 - Installation kind: [ bazel]
 - Using GPU/CUDA/CUDNN [NO]

**Operating System (please complete the following information):**
 - Distribution: [Ubuntu 16.04]
 - Bitness: [64bits]
 - Kernel details: [Linux alienwarem15 4.15.0-54-generic #58~16.04.1-Ubuntu SMP Mon Jun 24 13:21:41 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
]

**ROS (please complete the following information):**
 - Version: [kinetic]
 - Installation type: [from distribution]

**Describe the bug**

    fatal error: absl/strings/str_join.h: No such file or directory

I have this bug when i try to compile tensorflow_ros_test. I thought perhaps it wasnt updated with TF1.14, so i tried 1.8.0 but it's still there. I did a deeper dive into it and it seems like a tensorflow issue, but i havent managed to solve it. Did you do any workarounds?

I simply used the CMakelist from tensorflow_ros_test as an example when building.

**Additional context**
I wasnt sure how to link tensorflow. I cloned the official repo to ~/Documents/src/ build it with 
`bazel build --config=opt --define framework_shared_object=false tensorflow:libtensorflow_cc.so`

in tensorflow_ros_cpp CMakelists.txt, i changed a few lines to:
`set(TF_BAZEL_LIBRARY "/home/ryan/Documents/src/tensorflow/bazel-bin/tensorflow/libtensorflow_cc.so" CACHE STRING "Path to the bazel-compiled Tensorflow C++ library")`
`set(TF_BAZEL_SRC_DIR "/home/ryan/Documents/src/tensorflow" CACHE STRING "Path to the Tensorflow sources directory")`

In cmake/detect_tf/bazel.cmake i changed:

    list(APPEND TENSORFLOW_INCLUDE_DIRS ${BAZEL_TF_DIR}/external/com_google_protobuf/src)

**Comment by peci1** [comment]
Can you please post the output of CMake when setting up tensorflow_ros_cpp? Also, can you find the missing file manually on your computer? (e.g. by running `find / -name 'str_join.h'`)

**Comment by eraserpencil** [comment]
It would be in ~/.cache/bazel_<username>/a99d93e171a7f4e7897fed558052be4e/external/com_google_absl/absl/strings/str_join.h

**Comment by peci1** [comment]
If this file points to the same location where `${BAZEL_TF_DIR}/external/com_google_protobuf/src` would point, then the error is weird. Did you try completely cleaning the workspace after the CMake changes?

**Comment by peci1** [comment]
You can look at the exported include directories which are somewhere like `devel/share/tensorflow_ros_cpp/cmake/tensorflo_ros_cppConfig.cmake`, search around for `INCLUDE_DIRS`. The directory containing the missing file should be listed there (and if it's not, that would be the source of the problem).

**Comment by eraserpencil** [comment]
the directory is missing from /tensorflow_ros_cpp/cmake/tensorflo_ros_cppConfig.cmake.

**Comment by peci1** [comment]
Then you have to check how's that possible when you explicitly added the directory to `TENSORFLOW_INCLUDE_DIRS`. You can try populating the CMake file with some `message()` print statements to show the contents of variables at various states...

**Comment by eraserpencil** [comment]
added ` list(APPEND TENSORFLOW_INCLUDE_DIRS ${BAZEL_TF_DIR}/external/com_google_absl)` in cmake/detect_tf_bazel.cmake and finally everything builds fine.

Now, when i try to run tensorflow_ros_test, `error while loading shared libraries: libtensorflow_cc.so.1: cannot open shared object file: No such file or directory`

**Comment by peci1** [comment]
Ah, good to hear that! I already started to build TF via bazel on my own new machine to check that...

The problem with the `.so.1` is something added in TF 1.14. As a temporary fix, you can symlink the `.so` file to `.so.1` and that should satisfy the linker. I'll release a proper fix later.

**Comment by eraserpencil** [comment]
sorry to bother you again. 

I dont get the `.so.1` deal . I see tensorflow linking `.so` to `.so.1`, then `.so.1` to `.so.1.14.0`. So i'm not really sure why im getting the error. I need help tracing where `libtensorflow_cc.so.1` s referenced so i can see what's getting broken

**Comment by peci1** [comment]
Give a try to current master branch. I tried to fix both of these errors.

**Comment by eraserpencil** [comment]
sorry for the late response, just tried it with my ros project, works beautifully. Thanks alot!

**Comment by peci1** [comment]
Good! Thanks for the nicely written report and cooperation.
